In [ ]:
from collections import Counter
c = Counter()

c['red'] += 1

print (c)

In [ ]:
import sys
print(sys.version)

In [ ]:
from collections import OrderedDict

temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]

def check(temps):
    retdict = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))
    return retdict

print (check(temps))

### OrderedDict([('2001', -2.5), ('2000', -4.4), ('2002', -4.4), ('2003', -9.5)])

In [ ]:
from collections import deque

def brackets(line):
    stc = deque()
    for i, ch in enumerate(line):
        if line[i] == '(':
            stc.append(line[i])
        elif line[i] == ')':
            try:
                stc.pop()
            except IndexError:
                return False
    try:
        stc.pop()
        return False
    except IndexError:
        return True
    return True

print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False



In [ ]:
from collections import defaultdict
#import collections

dict_object = dict()
defaultdict_object = defaultdict()
 
print(type(dict_object))
# <class 'dict'>
print(type(defaultdict_object))
# <class 'collections.defaultdict'>

#center = defaultdict(None, [['Milk', 'Bread'], ['Meat']], ['Milk', 'Bread', 'Meat'])
#(center, south, north) = (1, 2, 3)

#print (center)

In [ ]:
# (ключ, значение)
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
client_ages = dict(data)
print(client_ages)

from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)

ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)

ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)

del ordered_client_ages['Andrey']
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18)])
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)

In [ ]:
from collections import deque
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
print(clients[2])

In [ ]:
i = 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13 + 14 + 15 + 16 + 17
print (i)

In [ ]:
from hidden import *
from collections import *

def flatten(S):
    if S == []:
        return S
    if isinstance(S[0], list):
        return flatten(S[0]) + flatten(S[1:])
    return S[:1] + flatten(S[1:])

c = list(center)
s = list(south)
n = list(north)

cc = Counter(flatten(c))
ss = Counter(flatten(s))
nn = Counter(flatten(n))
    
#print (cc)
#print (ss)
print (nn)

cc.

In [ ]:
from collections import *
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
cafes = OrderedDict(sorted(ratings, key=lambda x: (-x[1], x[0]), reverse=False))
print (cafes)

In [ ]:
from collections import *
def task_manager(tasks):
    dd = defaultdict(deque)
    for it in tasks:
        dq = deque(dd[it[1]])
        if it[2]:
            dq.appendleft(it[0])
        else:
            dq.append(it[0])
        dd[it[1]] = dq
    return dd

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]), 'office': deque([36871, 40690, 33850])})


In [ ]:
#!pip install numpy
import numpy as np
a = -456
print (a)

b = np.int8(a)
print (b)

In [ ]:
#!pip install numpy
import numpy as np
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)
print arr.

In [63]:
import numpy as np

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974., -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431., 29810.], dtype=np.float32)

nans_index = np.isnan(mystery)
n_nan = np.count_nonzero(np.isnan(mystery))
mystery_new = np.array(mystery, dtype=np.float32)
mystery_new[np.isnan(mystery_new)] = 0
#mystery_int = mystery.astype('int32')
array = np.sort(mystery)
#table = mystery.reshape((5,3), order='F')
table = np.array([[-26024.,  -2365.,  29810.,],
 [-17722.,  12279.,  31244.,],
 [-16431.,  16132.,     np.nan,],
 [ -9212.,  25933.,     np.nan,],
 [ -6974.,  28745.,     np.nan]], dtype=np.float32)
col = table[:,1]

print (mystery)
#print (nans_index)
#print (n_nan)
#print (mystery_new)
#print (mystery_int)
#print (array)
print (table)
print (col)

[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
[-2365. 12279. 16132. 25933. 28745.]


In [5]:
simplelist = [19, 242, 14, 152, 142, 1000]
print (sum(simplelist) / len(simplelist))

261.5
